class ReplaceW:
    def __init__(self, contents):
        self.contents = contents

    def word_modify(self):
        self.contents = self.contents.replace(',', '')
        self.contents = self.contents.replace('.', '')
        self.contents = self.contents.replace('·', '')
        self.contents = self.contents.replace(':', '')
        self.contents = self.contents.replace(';', '')
        self.contents = self.contents.replace('"', '')
        self.contents = self.contents.replace('\u200b', '')
        self.contents = self.contents.replace("'", '')
        self.contents = self.contents.replace("-", '')
        self.contents = self.contents.replace('_', '')
        self.contents = self.contents.replace('–', '')
        self.contents = self.contents.replace("\r ", '')
        self.contents = self.contents.replace("\n", '')
        self.contents = self.contents.replace("\xa0", '')
        self.contents = self.contents.replace('\\', '')
        self.contents = self.contents.replace('  ', ' ')
        self.contents = self.contents.replace('[', '')
        self.contents = self.contents.replace(']', '')
        self.contents = self.contents.replace('(', '')
        self.contents = self.contents.replace(')', '')
        self.contents = self.contents.replace('{', '')
        self.contents = self.contents.replace('}', '')
        self.contents = self.contents.replace('*', '')
        self.contents = self.contents.replace('“', '')
        self.contents = self.contents.replace('”', '')
        self.contents = self.contents.replace('¿', '')
        self.contents = self.contents.replace('?', '')
        self.contents = self.contents.replace('<', '')
        self.contents = self.contents.replace('>', '')
        self.contents = self.contents.replace('‘', '')
        self.contents = self.contents.replace('’', '')
        self.contents = self.contents.replace('VEA EL VIDEO', '')
        self.contents = self.contents.replace('VEA LA ENTREVISTA', '')
        self.contents = self.contents.replace('  ', ' ')
        self.contents = self.contents.replace('\r            ', '')
        return self.contents